---
# ⚙️ EQUIPO TRAEFIK + ACME - Load balancer y certificados automáticos
- name: "⚙️ ETAPA 2 - Configurar Traefik Load Balancer"
  hosts: traefik_servers
  become: yes
  
  pre_tasks:
    - name: "📦 Actualizar paquetes del sistema"
      apt:
        update_cache: yes
        upgrade: yes
        
  roles:
    - common
    - traefik
