---
# 📈 EQUIPO MONITOREO - Setup Prometheus + Grafana
- name: "📈 ETAPA 2 - Configurar Stack de Monitoreo"
  hosts: monitoring_servers
  become: yes
  vars_files:
    - ../../../teams/monitoring.yml

  tasks:
    - name: "📦 Instalar Docker y Docker Compose"
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: "🚀 Iniciar Docker"
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: "👥 Crear usuarios del equipo"
      user:
        name: "{{ item }}"
        groups: sudo,docker
        shell: /bin/bash
        create_home: yes
      loop: "{{ members }}"

    - name: "🔑 Configurar claves SSH"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '../../../users/' + item + '/id_rsa.pub') }}"
      loop: "{{ members }}"
      ignore_errors: yes

    - name: "📊 Crear directorio de monitoreo"
      file:
        path: /opt/monitoring
        state: directory
        owner: root
        group: docker
        mode: '0755'

    - name: "⚙️ Crear configuración de Prometheus"
      copy:
        content: |
          global:
            scrape_interval: {{ variables.scrape_interval }}
            
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
                
            - job_name: 'node-exporters'
              static_configs:
                - targets: 
                  - 'localhost:9100'
                  # Aquí se agregarán automáticamente los otros servidores
                  
            - job_name: 'nginx-exporters'
              static_configs:
                - targets: ['localhost:9113']
        dest: /opt/monitoring/prometheus.yml

    - name: "🐳 Crear Docker Compose para monitoreo"
      copy:
        content: |
          version: '3.8'
          services:
            prometheus:
              image: prom/prometheus:latest
              ports:
                - "9090:9090"
              volumes:
                - ./prometheus.yml:/etc/prometheus/prometheus.yml
                
            grafana:
              image: grafana/grafana:latest
              ports:
                - "3000:3000"
              environment:
                - GF_SECURITY_ADMIN_PASSWORD={{ variables.grafana_admin_password }}
              volumes:
                - grafana-storage:/var/lib/grafana
                
            node-exporter:
              image: prom/node-exporter:latest
              ports:
                - "9100:9100"
                
          volumes:
            grafana-storage:
        dest: /opt/monitoring/docker-compose.yml

    - name: "🚀 Levantar stack de monitoreo"
      docker_compose:
        project_src: /opt/monitoring
        state: present

    - name: "🔓 Abrir puertos necesarios"
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: "{{ ports }}"

    - name: "📈 Mostrar información del equipo"
      debug:
        msg:
          - "🎉 ¡EQUIPO MONITOREO CONFIGURADO!"
          - "👥 Miembros: {{ members | join(', ') }}"
          - "📊 Prometheus: http://{{ ansible_default_ipv4.address }}:9090"
          - "📈 Grafana: http://{{ ansible_default_ipv4.address }}:3000"
          - "🔑 Usuario Grafana: admin / {{ variables.grafana_admin_password }}"
