---
# 🔧 ROLE COMMON - Configuración base para todos los servidores
- name: "📦 Actualizar cache de paquetes"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "🔧 Instalar paquetes básicos"
  apt:
    name:
      - curl
      - wget
      - vim
      - htop
      - git
      - ufw
      - unzip
    state: present

- name: "👥 Crear usuarios del sistema"
  include_tasks: users.yml

- name: "🔥 Configurar firewall básico"
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: "🔓 Permitir SSH"
  ufw:
    rule: allow
    port: "22"

- name: "⏰ Configurar timezone"
  timezone:
    name: "{{ system_timezone | default('UTC') }}"
