---
- name: Actualizar caché de APT y todos los paquetes a la última versión
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
  tags:
    - packages
    - security

- name: Instalar paquetes comunes del sistema
  apt:
    name:
      - ufw
      - unattended-upgrades
      - fail2ban
      - htop
      - curl
      - wget
      - git
      - vim
      - tree
      - rsync
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
  tags:
    - packages

- name: Configurar actualizaciones automáticas de seguridad
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";
    mode: '0644'
    owner: root
    group: root
  tags:
    - security
    - packages

- name: Configurar UFW - denegar todo por defecto
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  tags:
    - security
    - firewall

- name: Configurar UFW - permitir servicios específicos
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - OpenSSH
    - Nginx Full
  tags:
    - security
    - firewall

- name: Configurar UFW - permitir puertos específicos si están definidos
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ additional_open_ports | default([]) }}"
  when: additional_open_ports is defined
  tags:
    - security
    - firewall

- name: Crear usuarios adicionales del sistema
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default('sudo') }}"
    shell: /bin/bash
    create_home: yes
    append: yes
  loop: "{{ system_users | default([]) }}"
  when: system_users is defined
  tags:
    - users

- name: Configurar claves SSH para usuarios
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ lookup('file', 'files/ssh_keys/' + item.1) }}"
    state: present
  with_subelements:
    - "{{ system_users | default([]) }}"
    - ssh_keys
    - skip_missing: true
  when: system_users is defined
  tags:
    - users
    - ssh

- name: Configurar límites de recursos del sistema
  pam_limits:
    domain: '*'
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - { type: 'soft', item: 'nofile', value: '65536' }
    - { type: 'hard', item: 'nofile', value: '65536' }
    - { type: 'soft', item: 'nproc', value: '4096' }
    - { type: 'hard', item: 'nproc', value: '4096' }
  tags:
    - performance

- name: Configurar timezone del sistema
  timezone:
    name: "{{ system_timezone | default('UTC') }}"
  tags:
    - system

- name: Habilitar y configurar servicios esenciales
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - fail2ban
    - unattended-upgrades
  tags:
    - security
    - services
