---
- name: Configuración rápida para testing
  hosts: webservers
  become: yes
  gather_facts: yes
  
  vars:
    # Configuración mínima para pruebas rápidas
    system_timezone: "UTC"
    
  pre_tasks:
    - name: Verificar conectividad
      ping:

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes
        upgrade: safe
      tags: packages

    - name: Instalar paquetes básicos
      apt:
        name:
          - curl
          - wget
          - htop
          - nginx
        state: present
      tags: packages

    - name: Iniciar Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
      tags: nginx

    - name: Crear página básica
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Test Server</title></head>
          <body>
          <h1>¡Servidor de prueba funcionando!</h1>
          <p>Configurado el: {{ ansible_date_time.iso8601 }}</p>
          <p>Host: {{ ansible_hostname }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      tags: nginx

  post_tasks:
    - name: Verificar estado de Nginx
      service_facts:

    - name: Mostrar resultado
      debug:
        msg: "Nginx está {{ ansible_facts.services['nginx.service'].state }}"
