---
# Playbook para configurar servidores del grupo LINT
- name: Configurar herramientas de linting
  hosts: lint_servers
  become: yes
  vars_files:
    - ../../groups/lint.yml

  tasks:
    - name: Actualizar paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar Node.js y npm
      apt:
        name: 
          - nodejs
          - npm
        state: present

    - name: Instalar Python y pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Instalar herramientas de linting
      shell: "{{ item.install_command }}"
      loop: "{{ tools }}"
      when: tools is defined

    - name: Crear usuarios del grupo lint
      user:
        name: "{{ item }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes
      loop: "{{ members }}"

    - name: Configurar claves SSH para usuarios
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '../../users/' + item + '/id_rsa.pub') }}"
      loop: "{{ members }}"
      ignore_errors: yes

    - name: Abrir puertos necesarios
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: "{{ ports }}"
      when: ports is defined
