# 🎯🤝 Inventario para Curso "Infra Made Easy"
# ETAPA 1: Individual | ETAPA 2: Equipos Colaborativos

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    # 📈 EQUIPO 1 - MONITOREO
    monitoring_servers:
      hosts:
        monitoring1:
          ansible_host: "{{ lookup('env', 'MONITORING_SERVER_IP') | default('127.0.0.1') }}"
      vars:
        team_type: monitoring
        
    # 🌍 EQUIPO 2 - WEBSERVER + SSL
    webserver_ssl_servers:
      hosts:
        webssl1:
          ansible_host: "{{ lookup('env', 'WEBSSL_SERVER_IP') | default('127.0.0.1') }}"
        webssl2:
          ansible_host: "{{ lookup('env', 'WEBSSL_SERVER_IP_2') | default('127.0.0.1') }}"
      vars:
        team_type: webserver-ssl
        
    # 🔒 EQUIPO 3 - SEGURIDAD
    security_servers:
      hosts:
        security1:
          ansible_host: "{{ lookup('env', 'SECURITY_SERVER_IP') | default('127.0.0.1') }}"
      vars:
        team_type: security-lynis
        
    # 🔄 EQUIPO 4 - CI/CD
    cicd_servers:
      hosts:
        cicd1:
          ansible_host: "{{ lookup('env', 'CICD_SERVER_IP') | default('127.0.0.1') }}"
      vars:
        team_type: cicd
        
    # ⚙️ EQUIPO 5 - TRAEFIK
    traefik_servers:
      hosts:
        traefik1:
          ansible_host: "{{ lookup('env', 'TRAEFIK_SERVER_IP') | default('127.0.0.1') }}"
      vars:
        team_type: traefik-acme
