# 🎯🤝 Inventario para Curso "Infra Made Easy"
# Estructura correcta con children y grupos jerárquicos

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    # 🔧 GRUPO PRINCIPAL - TODOS LOS SERVIDORES DEL CURSO
    common:
      children:
        webservers:
        monitoring:
        infrastructure:
        students:
    
    # 🌐 GRUPO WEBSERVERS - Todos los servidores web
    webservers:
      children:
        webserver_ssl_servers:
        security_servers:
      vars:
        server_category: web
    
    # 📊 GRUPO MONITOREO - Servicios de observabilidad
    monitoring:
      children:
        monitoring_servers:
      vars:
        server_category: monitoring
    
    # 🔧 GRUPO INFRAESTRUCTURA - Servicios de soporte
    infrastructure:
      children:
        cicd_servers:
        traefik_servers:
      vars:
        server_category: infrastructure
        
    # 🎯 GRUPO ESTUDIANTES - Servidores individuales Etapa 1
    students:
      children:
        student_servers:
      vars:
        server_category: student

# ========================
# 📈 SERVIDORES ESPECÍFICOS
# ========================

# 📈 EQUIPO 1 - MONITOREO
monitoring_servers:
  hosts:
    monitoring1:
      ansible_host: "{{ lookup('env', 'MONITORING_SERVER_IP') | default('127.0.0.1') }}"
      server_name: "prometheus-grafana-1"
    monitoring2:
      ansible_host: "{{ lookup('env', 'MONITORING_SERVER_IP_2') | default('127.0.0.1') }}"
      server_name: "prometheus-grafana-2"
  vars:
    team_type: monitoring
    
# 🌍 EQUIPO 2 - WEBSERVER + SSL
webserver_ssl_servers:
  hosts:
    webssl1:
      ansible_host: "{{ lookup('env', 'WEBSSL_SERVER_IP') | default('127.0.0.1') }}"
      server_name: "nginx-ssl-1"
      domain: "web1.curso-infra.com"
    webssl2:
      ansible_host: "{{ lookup('env', 'WEBSSL_SERVER_IP_2') | default('127.0.0.1') }}"
      server_name: "nginx-ssl-2"
      domain: "web2.curso-infra.com"
    webssl3:
      ansible_host: "{{ lookup('env', 'WEBSSL_SERVER_IP_3') | default('127.0.0.1') }}"
      server_name: "nginx-ssl-3"
      domain: "web3.curso-infra.com"
  vars:
    team_type: webserver-ssl
    
# 🔒 EQUIPO 3 - SEGURIDAD
security_servers:
  hosts:
    security1:
      ansible_host: "{{ lookup('env', 'SECURITY_SERVER_IP') | default('127.0.0.1') }}"
      server_name: "lynis-security-1"
  vars:
    team_type: security-lynis
    
# 🔄 EQUIPO 4 - CI/CD
cicd_servers:
  hosts:
    cicd1:
      ansible_host: "{{ lookup('env', 'CICD_SERVER_IP') | default('127.0.0.1') }}"
      server_name: "jenkins-cicd-1"
    cicd2:
      ansible_host: "{{ lookup('env', 'CICD_SERVER_IP_2') | default('127.0.0.1') }}"
      server_name: "jenkins-cicd-2"
  vars:
    team_type: cicd
    
# ⚙️ EQUIPO 5 - TRAEFIK
traefik_servers:
  hosts:
    traefik1:
      ansible_host: "{{ lookup('env', 'TRAEFIK_SERVER_IP') | default('127.0.0.1') }}"
      server_name: "traefik-lb-1"
  vars:
    team_type: traefik-acme

# 🎯 ETAPA 1 - SERVIDORES INDIVIDUALES ESTUDIANTES
student_servers:
  hosts:
    my-server:
      ansible_host: "{{ lookup('env', 'MY_SERVER_IP') | default('127.0.0.1') }}"
      student_name: "{{ lookup('env', 'STUDENT_NAME') | default('estudiante') }}"
    # Cada estudiante puede agregar su servidor individual aquí:
    # juan-server:
    #   ansible_host: "1.2.3.4"
    #   student_name: "juan"
    # maria-server:
    #   ansible_host: "5.6.7.8"
    #   student_name: "maria"
  vars:
    team_type: student
    server_category: individual
