---
collections:
  - name: amazon.aws
    version: ">=6.0.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.crypto
    version: ">=2.0.0"

roles:
  # Ejemplo: roles externos que podrías querer usar
  # - name: geerlingguy.security
  #   version: "2.0.1"
  # - name: geerlingguy.docker
  #   version: "6.1.0"
